### ISSUE TITLE
pull_request で成果物を「Artifacts」として添付

### ISSUE THREAD

**Issue by ao-39** [ao-39/study_github_agent#36]
pull_request で成果物を「Artifacts」として添付する。
apps/appに関してビルドした成果物をPRからダウンロードできるようにします。

必要な場合はzipなどにします。必要なければそのまま配信します。

以下を参考にする。

<html>
<body>
<h2>① pull_request で成果物を「Artifacts」として添付</h2>
<p><strong>特徴</strong></p>

✅ 長所 | ⚠️ 注意点
-- | --
- PR の Checks 画面に自動で Artifacts リンクが表示されるので、レビュワーがすぐダウンロード可能 | - 保存期間はデフォルト 90 日（超えると自動削除）GitHub Docs
- 権限は repo を閲覧できる人 に限定され、外部公開しないテスト版に最適 | - 永続公開したい場合は後述②/③へ

<p><strong>最小サンプル</strong></p>
<pre><code class="language-yaml">yaml
コピーする編集する
# .github/workflows/pr-artifact.yml
name: Build (PR)
on:
  pull_request: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         # コードを取得
      - run: npm ci &amp;&amp; npm run build      # ビルド
      - run: zip -r dist.zip dist/        # 成果物を ZIP 化
      - uses: actions/upload-artifact@v4  # アップロード:contentReference[oaicite:1]{index=1}
        with:
          name: dist-${{ github.sha }}.zip
          path: dist.zip
          retention-days: 14              # 必要に応じて延長

</code></pre>
<blockquote>
<p>🌟 ワンポイント：</p>
<p>PR に「ダウンロードはこちら👉」と自動コメントしたい場合は、最後に</p>
<p><code>peter-evans/create-or-update-comment@v4</code> などで <code>https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts</code> を貼り付けると UX がさらに向上します。</p>
</blockquote>

</body>
</html>## ① pull_request で成果物を「Artifacts」として添付

**特徴**

| ✅ 長所 | ⚠️ 注意点 |
| --- | --- |
| - PR の Checks 画面に自動で *Artifacts* リンクが表示されるので、レビュワーがすぐダウンロード可能 | - 保存期間はデフォルト 90 日（超えると自動削除）[[GitHub Docs](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/downloading-workflow-artifacts?utm_source=chatgpt.com)](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/downloading-workflow-artifacts?utm_source=chatgpt.com) |
| - 権限は *repo を閲覧できる人* に限定され、外部公開しないテスト版に最適 | - 永続公開したい場合は後述②/③へ |

**最小サンプル**

```yaml
yaml
コピーする編集する
# .github/workflows/pr-artifact.yml
name: Build (PR)
on:
  pull_request: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         # コードを取得
      - run: npm ci && npm run build      # ビルド
      - run: zip -r dist.zip dist/        # 成果物を ZIP 化
      - uses: actions/upload-artifact@v4  # アップロード:contentReference[oaicite:1]{index=1}
        with:
          name: dist-${{ github.sha }}.zip
          path: dist.zip
          retention-days: 14              # 必要に応じて延長

```

> 🌟 ワンポイント：
> 
> 
> PR に「ダウンロードはこちら👉」と自動コメントしたい場合は、最後に
> 
> `peter-evans/create-or-update-comment@v4` などで `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts` を貼り付けると UX がさらに向上します。
>
