### ISSUE TITLE
dependabot対応

### ISSUE THREAD

**Issue by ao-39** [ao-39/study_github_agent#61]
dependabotが有効になるようにdependabot.ymlを追加する。

必要なオプションを分析提案して、実装していくこと。

以下を参考にする。

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```
